version: "3"

# Docker compose override to enable traefik plain HTTP settings.

services:
  # unified origin
  origin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.origin.entrypoints=web"
      - "traefik.http.routers.origin.rule=PathPrefix(`/`)"

  # Virtual Channel application
  virtual-channel-api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=api"
      - "traefik.http.routers.api.rule=PathPrefix(`/`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

  # Manifest Proxy application
  manifest-proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manifest-proxy.rule=Path(`/{manifest:.*\\.ism[l]?/.*\\.(mpd|m3u8)}`)"
      - "traefik.http.routers.manifest-proxy.entrypoints=web"

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.api.address=:8000"
      - "--entryPoints.api.forwardedHeaders.insecure"
    ports:
      - ${ORIGIN_PORT}:80
      - ${API_PORT}:8000
