## STATIC CONFIG (restart traefik to update)

# log default is ERROR, but WARN is more helpful
log:
  level: WARN

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    fileName: /etc/traefik/traefik.yaml
    watch: true

# listen on 80/443, and 8000/8443 and redirect all 80/8000 to 443/8443 via 301
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  api:
    address: :8000
    http:
      redirections:
        entryPoint:
          to: apisecure
          scheme: https
          permanent: true
  apisecure:
    address: :8443
    forwardedHeaders:
      insecure: true


## DYNAMIC CONFIG

tls:
  certificates:
    - certFile: /certs/replace_this_with_your_cert_filename.crt
      keyFile: /certs/replace_this_with_your_key_filename.key
